// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AkarIconsCircleCheckFill: typeof import('~icons/akar-icons/circle-check-fill')['default']
    BxBxEditAlt: typeof import('~icons/bx/bx-edit-alt')['default']
    CarbonClose: typeof import('~icons/carbon/close')['default']
    DeliveryTo: typeof import('./components/delivery-to/index.vue')['default']
    IconAccessibility: typeof import('~icons/ic/on-accessibility')['default']
    TButton: typeof import('./components/t-button/t-button.vue')['default']
    TIcon: typeof import('./components/t-icon/t-icon.vue')['default']
    TPopup: typeof import('./components/t-popup/t-popup.vue')['default']
    TTag: typeof import('./components/t-tag/t-tag.vue')['default']
    TWrapper: typeof import('./components/t-wrapper/t-wrapper.vue')['default']
    WxIcon: typeof import('./components/wx-icon/index.vue')['default']
  }
}

export { }
